### Valid Request - Easy Difficulty with Science Category
POST {{baseUrl}}/sessions
Content-Type: application/json

{
  "difficultyLevel": "EASY",
  "category": "SCIENCE"
}



### Valid Request - Hard Difficulty with Sports Category
POST {{baseUrl}}/sessions
Content-Type: application/json

{
  "difficultyLevel": "HARD",
  "category": "SPORTS"
}



### Invalid Request - Missing Difficulty Level
POST {{baseUrl}}/sessions
Content-Type: application/json

{
  "category": "LITERATURE"
}



### Invalid Request - Missing Category
POST {{baseUrl}}/sessions
Content-Type: application/json

{
  "difficultyLevel": "MEDIUM"
}



### Invalid Request - Invalid Difficulty Level
POST {{baseUrl}}/sessions
Content-Type: application/json

{
  "difficultyLevel": "EXTREME",
  "category": "SCIENCE"
}



### Invalid Request - Invalid Category
POST {{baseUrl}}/sessions
Content-Type: application/json

{
  "difficultyLevel": "MEDIUM",
  "category": "UNKNOWN_CATEGORY"
}



### Valid Request - Medium Difficulty with Pop Culture Category
POST {{baseUrl}}/sessions
Content-Type: application/json

{
  "difficultyLevel": "MEDIUM",
  "category": "POP_CULTURE"
}



### Complete Quiz Session with Some Incorrect Answers
POST http://localhost:8080/api/v1/sessions/0f44e39a-69c6-49ec-91e6-9e0f60abdf05/complete
Content-Type: application/json

{
  "selectedAnswers": [
    [
      "H2O"
    ],
    [
      "Mars"
    ],
    [
      "Oxygen"
    ],
    [
      "Mitochondria"
    ],
    [
      "Gravity"
    ],
    [
      "Dolphin"
    ],
    [
      "100°C"
    ],
    [
      "Wind"
    ],
    [
      "Cell"
    ],
    [
      "Light"
    ]
  ]
}







