spring:
  application:
    name: quizz-app-backend
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    baseline-on-migrate: true
    enabled: true
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    time-zone: UTC
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}

server:
  port: 8080
  servlet:
    context-path: /api

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate.SQL: WARN