spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  flyway:
    password: ${DB_USERNAME}
    user: ${DB_PASSWORD}

logging:
  level:
    root: info
    org.iamflubin.quiz: INFO
    org.springframework: INFO
    org.hibernate.SQL: OFF
    org.hibernate.type: OFF