spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/quizz_db
    username: root
    password: root
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    password: root
    user: root

logging:
  level:
    #root: DEBUG
    org.iamflubin.quiz: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE
    #org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    #org.springframework: DEBUG
    org.springframework:
      orm.jpa: DEBUG
      transaction.interceptor: DEBUG
      ai.chat.client.advisor: DEBUG
